### ISSUE TITLE
Text ended before matching quote was found for ".

### ISSUE THREAD

**Issue by sphh** [Odyseus/CinnamonTools#10]
Hi,

Whenever I start cinnamon with Custom Cinnamon Menu I get the following error message:

Execution of 'chmod +x "/home/$USER/.local/share/cinnamon/applets/0dyseus@CustomCinnamonMenu/run_from_terminal.sh' failed:

Text ended before matching quote was found for ". (The text was 'chmod +x "/home/$USER/.local/share/cinnamon/applets/0dyseus@CustomCinnamonMenu/run_from_terminal.sh')

**Comment by Odyseus** [comment]
Hello, @sphh.
Thanks for the error report. I just fixed this issue. In about 24 hours the update for this Custom Cinnamon Menu applet might be available from Cinnamon Settings. Or you could simply update it manually.

**Comment by sphh** [comment]
Hi,

Thank you for the prompt action!

That's exactly what I did: I added the executable bit to the script file.

Stephan
