### ISSUE TITLE
improve menu performance

### ISSUE THREAD

**Issue by fortalezense** [Odyseus/CinnamonTools#11]
I'm writing here the same request I made for CinnXPStarkMenu: https://github.com/NikoKrause/CinnXPStarkMenu/issues/8

The Cinnamon stock menu is great. It uses directional detection in order to provide a better navigation. You can read a lot of good information here: linuxmint/Cinnamon#1775
But to implement directional detection, Cinnamon draws a polygon (a vector box) in the menu. That uses precious resources. @lestcape created other solution for this feature that seems to be more efficient. You can read about it here: linuxmint/Cinnamon#4464 and here: linuxmint/Cinnamon#4854

So I suggest implementing lestcape's solution into Custom Cinnamon Menu.

**Comment by Odyseus** [comment]
Hello, @fortalezense.
I can't promise anything, but I will see what can be done.

**Comment by Odyseus** [comment]
Hello, @fortalezense.

Just in case you want to test it, I implemented **lestcape**'s method into my Custom Cinnamon Menu applet. In my main system, I couldn't see the gain in performance. But then I tried it in one of my virtual machines and I could *feel* the difference.

**Comment by lestcape** [comment]
@Odyseus Test it in a virtual machine it's a good way to detected the difference also you can reduce the hardware of the virtual machine and you will notice the difference more...

**Comment by Odyseus** [comment]
Hello, @lestcape.

Yes. I'm forced to use rendering mode (3D acceleration disabled) on my virtual machines with Cinnamon. So, when I test something, I can see very clear the change in performance.

**Comment by fortalezense** [comment]
Hi, @Odyseus . Sorry for taking so much time to reply. Thank you very much for implementing this feature/optimization.  Indeed I've not seen clearly a noticeable gain in performance, but my machine is pretty decent. I suspect that on less powerful machines the performance improvement might be more significant. In fact, I'm very happy for this enhancement. I think we should always try to improve performance whenever there is an opportunity like that. Maybe with other small tweaks we can get a more perceptible result in the near future.
