### ISSUE TITLE
Desktop Handler - Configuration from context menu

### ISSUE THREAD

**Issue by Radek71** [Odyseus/CinnamonTools#126]
@Odyseus 

I am not able to open the configuration window for this applet from applet context menu. Other items in the context menu works properly (Help/About/Remove). From Cinnamon applet manager is still possible to open configuration window. Could you please check if there is not bug?

Thanks

Radek

**Comment by Odyseus** [comment]
Thanks for the report, @Radek71. 👍 

Already fixed in this repository and published on the Spices repository.
