### ISSUE TITLE
menu applet: Tooltips fixed width

### ISSUE THREAD

**Issue by NikoKrause** [Odyseus/CinnamonTools#13]
![tooltip](https://cloud.githubusercontent.com/assets/8415124/20860002/66d7859a-b96e-11e6-9208-2c4d2555af2c.png)
You are using a fixed width for the Tooltips. This leads to a lot of blank space at the right of the tooltip, if the Tooltip uses more than one line.

I would recommend to do something similar, like I do in StarkMenu. I have improved it a little bit. I created a `TooltipsCustom` function. I have to improve it a little bit and am pushing it next week. I'll send you the link then.
The idea behind my stuff is the following code:
```js
function TooltipCustom(actor, string, multiline) {
    this._init(actor, string, multiline);
}

TooltipCustom.prototype = {
    __proto__: Tooltips.Tooltip.prototype,

    _init: function(actor, string, multiline) {
        let formatString = string;
        if (multiline) {
            let lastSpacePos = -1;
            let tooltipWidth = 80;
            let tooltipLines = Math.ceil(1.0 * formatString.length / tooltipWidth) - 1;

            for (let i = 0; i < tooltipLines; i++) {
                lastSpacePos = formatString.lastIndexOf(" ", lastSpacePos + tooltipWidth);
                formatString = formatString.replaceAt(lastSpacePos, "\n");
            }
        }

        if(formatString == "null")
            formatString = _("No description available");

        Tooltips.Tooltip.prototype._init.call(this, actor, formatString);
        this._tooltip.set_style("text-align: left;");
        this._tooltip.get_clutter_text().set_line_wrap(true);
        this._tooltip.get_clutter_text().set_line_wrap_mode(Pango.WrapMode.WORD_CHAR);
        this._tooltip.get_clutter_text().ellipsize = Pango.EllipsizeMode.NONE;
    }
};
```
I say one line in the tooltip is allowed to have 80 characters maximum.
I check, if the Tooltip is longer than 80 characters long. If that's the case, I check, where the last space in the first 80 characters is located and replace it with a linebreak `\n`.
Then I do the same for the next 80 characters.

Downside of this method is, that it looks ugly, when the Tooltip has a word, which is longer then 80 characters. But I'm not aware of such long words. The maximum of 80 can be changed, if needed.

P.S.: I saw this line here in your code:
```js
        // Ensure tooltip is destroyed when this button is destroyed
        this.connect("destroy", Lang.bind(this, function() {
            this.tooltip.destroy();
        }));
```
What is it good for. What happens, when I don't have it in my menu?

**Comment by Odyseus** [comment]
Hello, @NikoKrause.

I'm aware of that nuisance, but I prefer to keep it simple and straight to the point.

In addition to the possible overhead on tooltip creation that that code could introduce, I see another big problem with your approach. If you don't set a max-width, the word wrapping is never triggered. So, this code...
```javascript
this._tooltip.get_clutter_text().set_line_wrap(true);
this._tooltip.get_clutter_text().set_line_wrap_mode(Pango.WrapMode.WORD_CHAR);
this._tooltip.get_clutter_text().ellipsize = Pango.EllipsizeMode.NONE;
```

...will never take any effect.

You should choose one thing or the other. Both approaches can't coexist.

> P.S.: I saw this line here in your code:

I learned how to create tooltips with markup from the applet called [News feed reader](https://cinnamon-spices.linuxmint.com/applets/view/149). That code is in that applet. Initially, I thought that, if you insert an element inside another element (a tooltip inside a menu item, for example), then when the parent element is destroyed, the inserted element is also destroyed. That's DOM 101 (basics). But I have seen so many things that doesn't make sense in Clutter and Gtk elements, that I opted for including that line of code, even that I still think that it doesn't make any sense.

My initial intention was to create one unique and global tooltip, and then dynamically set/unset its content and position. I do this constantly in Firefox, one tooltip element can be used by any other element. But it seems that with Clutter, that isn't possible.

**Comment by NikoKrause** [comment]
Thanks. I'll remove that part.
Since you are aware of that issue, you can close it, if you want to.
