### ISSUE TITLE
Czech translation for Extension Manager applet

### ISSUE THREAD

**Issue by Radek71** [Odyseus/CinnamonTools#14]
[0dyseus@ExtensionsManager.po.zip](https://github.com/Odyseus/CinnamonTools/files/680482/0dyseus.ExtensionsManager.po.zip)

**Comment by Odyseus** [comment]
Hello, @Radek71.

Thank you very much for your contribution.

While looking at the applet's code, I realized that a couple of strings needed to be translated. I translated those strings to Czech by myself. Let me know if they are correct.

Name > Jméno
Description > Popis

I already uploaded the updated applet to this repository. I will wait for your feedback to upload it to the Spices website.

**Comment by Radek71** [comment]
Hi,

if the strings are for tooltips box (hint) - see attached picture, then the better translation is:
Name > Název
Description > Popis
![obrazek](https://cloud.githubusercontent.com/assets/20898211/21593936/27475e84-d11d-11e6-902b-9f48cd2ed2c6.png)

thanks
radek

**Comment by Odyseus** [comment]
Hello, @Radek71.

I already updated this repository with the correct word in Czech. Sadly, I cannot update the applet on the Spices website at this time because it seems that the developers are updating the website (they are changing de design and other things).

Just in case, remember that if you install de applet manually, you also have to install de translation manually using the **localizations.sh** script found inside the applet's folder.

**Comment by Radek71** [comment]
@Odyseus 

please add the missing strings to .pot file:
Icon size for the extension logo
Icon size for the extension option buttons

thanks

radek

**Comment by Odyseus** [comment]
Hello, @Radek71.

> please add the missing strings to .pot file:

Done. Thanks for the report. 👍

**Comment by Radek71** [comment]
Hello, @Odyseus 

here is updated Czech translation for v1.06
[0dyseus@ExtensionsManager.po.zip](https://github.com/Odyseus/CinnamonTools/files/984176/0dyseus.ExtensionsManager.po.zip)

**Comment by Radek71** [comment]
@Odyseus 

updated Czech translation for 1.07 is attached
[0dyseus@ExtensionsManager.po.zip](https://github.com/Odyseus/CinnamonTools/files/1034839/0dyseus.ExtensionsManager.po.zip)

There is not "Help" item in the context menu of the applet (nor in the settings window). Could you please add the possibility for easy open the help file?

thanks 

radek

**Comment by Odyseus** [comment]
> There is not "Help" item in the context menu of the applet...

Thanks for the report, @Radek71. I saw that missing item on the context several months ago, but I completely forgot about adding it. Added and uploaded. 👍

**Comment by Radek71** [comment]
@Odyseus 

updated Czech translation for 1.07 is attached
[0dyseus@ExtensionsManager.po.zip](https://github.com/Odyseus/CinnamonTools/files/1059903/0dyseus.ExtensionsManager.po.zip)

**Comment by Radek71** [comment]
@Odyseus 

updated Czech translation for 1.08 is attached
[0dyseus@ExtensionsManager.po.zip](https://github.com/Odyseus/CinnamonTools/files/1122919/0dyseus.ExtensionsManager.po.zip)
