### ISSUE TITLE
Czech translation for CinnamonTweaks extension 

### ISSUE THREAD

**Issue by Radek71** [Odyseus/CinnamonTools#15]
[0dyseus@CinnamonTweaks.po.zip](https://github.com/Odyseus/CinnamonTools/files/682936/0dyseus.CinnamonTweaks.po.zip)

**Comment by Odyseus** [comment]
Thanks again for your contribution, @Radek71.

I already uploaded the extension with your localization to this repository. It seems that in the Spices website will not be possible to edit existing applets/extensions for a couple of weeks until de developers finish the changes to the website.

An observation. It seems that you created this .po file manually based on the .pot file from the Extensions Manager applet. I recommend you to follow [this wiki](https://github.com/Odyseus/CinnamonTools/wiki/Xlet-localizations) that I created to create localization files. You will work much faster and will avoid possible errors.

**Comment by Radek71** [comment]
@Odyseus 

I am working on the update of Czech translation (1.08) and seems that some strings are missing in .pot file:

Before "****...." item (and other items from this selection)
Last item on menu
Bottom-right of screen
Top-right of screen
pixels
...is immediate (and other items from this selection)
Default behavior (and other items from this selection)
About
Contributors/Mentions

Could you please check it and update the pot file?

thanks

radek

**Comment by Odyseus** [comment]
Hello, @Radek71.

Good catch. I spotted other missing translatable strings on the settings.py file and already added them. But I also spotted an error on the logic the about dialog works, so it will take me some time to debug it.

When I'm finished with the changes, I will "ping you" in this issue.

Like always, thank you very much for your feedback. 👍

**Comment by Odyseus** [comment]
@Radek71

I already added all missing strings and made some modifications to the about dialog. All should be translatable now.

@muzena: The Croatian localization for Cinnamon Tweaks extension will also need updating.

**Comment by Radek71** [comment]
@Odyseus 

updated czech translation for 1.08 is attached
[0dyseus@CinnamonTweaks.po.zip](https://github.com/Odyseus/CinnamonTools/files/900504/0dyseus.CinnamonTweaks.po.zip)

**Comment by Radek71** [comment]
@Odyseus 

updated czech translation for 1.10 is attached
[0dyseus@CinnamonTweaks.po.zip](https://github.com/Odyseus/CinnamonTools/files/983837/0dyseus.CinnamonTweaks.po.zip)

**Comment by Radek71** [comment]
@Odyseus 

updated czech translation for 1.11 is attached
[0dyseus@CinnamonTweaks.po.zip](https://github.com/Odyseus/CinnamonTools/files/1059880/0dyseus.CinnamonTweaks.po.zip)

**Comment by Radek71** [comment]
@Odyseus 

updated czech translation for 1.12 is attached
[0dyseus@CinnamonTweaks.po.zip](https://github.com/Odyseus/CinnamonTools/files/1122923/0dyseus.CinnamonTweaks.po.zip)

**Comment by Radek71** [comment]
@Odyseus 

updated czech translation for 1.14 is attached
[0dyseus@CinnamonTweaks.po.zip](https://github.com/Odyseus/CinnamonTools/files/1221268/0dyseus.CinnamonTweaks.po.zip)
