### ISSUE TITLE
PopupTranslator: Tooltip says unmet dependencies, Popup says all dependencies met

### ISSUE THREAD

**Issue by NikoKrause** [Odyseus/CinnamonTools#22]
![bildschirmfoto vom 2017-02-03 08-46-08](https://cloud.githubusercontent.com/assets/8415124/22583572/ac8efb40-e9ed-11e6-903f-26b49fd2d1d2.png)

EDIT: There is nothing in the glass log

**Comment by Odyseus** [comment]
Hello, @NikoKrause.

Thanks for the report, NikoKrause.

This "multiversion businesses" is starting to pissing me off. I forgot again to copy over the applet.js file from the applet's root folder into the 3.2 folder. Already fixed on this repository. Creating PR for spices repository.
