### ISSUE TITLE
Popup Translator: Leo as translation provider

### ISSUE THREAD

**Issue by sphh** [Odyseus/CinnamonTools#24]
Hi,

Would it be possible to add www.leo.org as a translation service?

The drawbacks might be, that Leo is only available for some languages and that it is not a translation service but a dictionary. But it's great to look up single words or simple phrases (which I do most of the time).

**Comment by Odyseus** [comment]
Hello, @sphh.

I'm open to suggestions about adding more translation services, but they must have a documented [API](https://en.wikipedia.org/wiki/Application_programming_interface) and be free. The site that you suggest doesn't seem to have an API (neither paid nor free), so it will not be possible for me to add it to my applet.

I created this applet as a replacer of a [custom button that I created](http://custombuttons.sourceforge.net/forum/viewtopic.php?f=4&t=3632). In that button I also use the services of Microsoft Translator. But Microsoft changed its API and also they require an Azure account. It's still all free, but to have an Azure account, one must give a credit card number. So, that's is something that is never going to happen.

If you know of any other translation service that has a public API and it is free, feel free to suggest it and I will try to add it to my applet.

**Comment by sphh** [comment]
Hi,

You are perfectly right re Leo. I did not spot the [Development of toolbars/plug-ins/applets and the like](https://dict.leo.org/pages/about/ende/termsOfUsage_en.html#copyrightToolbars) in Leo's terms and conditions. A pity, because it's one of the best dictionaries available.

**Comment by NikoKrause** [comment]
@sphh 
You can use the "Internet Search Box" for that.
In the settings set to use a custom provider and something like that for the url `http://dict.leo.org/german-english/`
