### ISSUE TITLE
Window list; Feature request

### ISSUE THREAD

**Issue by abdulqader4000** [Odyseus/CinnamonTools#26]
hello
your window list is a great work.. liked it
but why it cant add or display pinned apps?

regards.

**Comment by Odyseus** [comment]
Hello, @abdulqader4000.

My Window list applet is a fork of the original applet that comes with Cinnamon. As such, my goal is to keep the applet as close to the original code as possible so it's easy to maintain.

Adding a feature such as *pinned apps* isn't something that I want/need nor do I see the point to it.
