### ISSUE TITLE
Czech translation for Multi Translator extension

### ISSUE THREAD

**Issue by Radek71** [Odyseus/CinnamonTools#41]
@Odyseus 

I am working on the Czech translation and seems that some strings are missing in .pot file:

Custom ( for selection of the timestamp format)
pixels
 - for setting percentage width/height should be used symbol % instead of the pixels inside the brackets ?
About
Help

Could you please check it and update the pot file?

thanks

radek

**Comment by Odyseus** [comment]
Hello, @Radek71.

The *Custom*, *About* and *Help* strings were already on the .pot file. I always ignore the *pixels* string because it is already translated by Cinnamon. It didn't show up translated because I didn't use the **_()** function to actually translate that string. Either way, I  just pushed a commit in which I added the *pixels* string to be correctly translated.

Like always, thanks for your feedback, Radek71. 👍

**Comment by Radek71** [comment]
@Odyseus 

thanks for fast update, but could you doublecheck this again:

1)"Custom" string for selection of the theme is translated correctly but for selection of the timestamp format is not translated.

2)For setting percentage width/height should be used symbol "%" or word "percent" instead of the "pixels" inside the brackets.

thanks
radek

**Comment by Odyseus** [comment]
Corrected the two errors reported in your last message. Y also added a couple more missing strings.

Thanks again, @Radek71. 👍

**Comment by Radek71** [comment]
@Odyseus 

attached is Czech translation and css file for my Thunderbolt theme.

Thanks for your nice work

radek
[0dyseus@MultiTranslatorExtension.po.zip](https://github.com/Odyseus/CinnamonTools/files/931717/0dyseus.MultiTranslatorExtension.po.zip)
[Thunderbolt.css.zip](https://github.com/Odyseus/CinnamonTools/files/931721/Thunderbolt.css.zip)

**Comment by Radek71** [comment]
@Odyseus 

updated Czech translation for v1.03
[0dyseus@MultiTranslatorExtension.po.zip](https://github.com/Odyseus/CinnamonTools/files/983881/0dyseus.MultiTranslatorExtension.po.zip)

**Comment by Radek71** [comment]
@Odyseus 

updated Czech translation for v1.04
[0dyseus@MultiTranslatorExtension.po.zip](https://github.com/Odyseus/CinnamonTools/files/1059961/0dyseus.MultiTranslatorExtension.po.zip)

**Comment by Radek71** [comment]
@Odyseus 

updated czech translation for 1.05 is attached
[0dyseus@MultiTranslatorExtension.po.zip](https://github.com/Odyseus/CinnamonTools/files/1122933/0dyseus.MultiTranslatorExtension.po.zip)

**Comment by Radek71** [comment]
@Odyseus 

updated czech translation for 1.07 is attached
[0dyseus@MultiTranslatorExtension.po.zip](https://github.com/Odyseus/CinnamonTools/files/1221269/0dyseus.MultiTranslatorExtension.po.zip)
