### ISSUE TITLE
Applet not working on Arch Linux

### ISSUE THREAD

**Issue by buzz** [Odyseus/CinnamonTools#5]
The applet loads but the graphs are never updated. Cinnamon debugger shows this while loading the applet:

```
error t=2016-10-06T15:45:52Z dev is null
trace t=2016-10-06T15:45:52Z 
<----------------
NetDataProvider.prototype._init@/home/buzz/.local/share/cinnamon/applets/0dyseus@SysmonitorByOrcus/applet.js:505
NetDataProvider@/home/buzz/.local/share/cinnamon/applets/0dyseus@SysmonitorByOrcus/applet.js:496
MyApplet.prototype._init@/home/buzz/.local/share/cinnamon/applets/0dyseus@SysmonitorByOrcus/applet.js:126
MyApplet@/home/buzz/.local/share/cinnamon/applets/0dyseus@SysmonitorByOrcus/applet.js:67
main@/home/buzz/.local/share/cinnamon/applets/0dyseus@SysmonitorByOrcus/applet.js:635
createApplet@/usr/share/cinnamon/js/ui/appletManager.js:329
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:256
finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:59
loadExtension@/usr/share/cinnamon/js/ui/extension.js:451
init@/usr/share/cinnamon/js/ui/appletManager.js:46
start@/usr/share/cinnamon/js/ui/main.js:453
@<main>:1
---------------->
info t=2016-10-06T15:45:52Z Loaded applet 0dyseus@SysmonitorByOrcus in 15 ms
```

The applet states this as dependency: `gir1.2-gtop-2.0`
I cannot install this package as I'm on Arch and not Ubuntu. But I checked this package and it installs the file `GTop-2.0.typelib`. That file is available on my system through the `libgtop 2.34.0` package.

Versions:
Cinnamon 3.0.7
Arch Linux 4.7.6 x86_64

**Comment by buzz** [comment]
I figured the applet uses `NMClient.Client.new().get_devices()` to get the network devices. NetworkManager is not running on my system and as a result the code failed.

I replaced this with `GTop.glibtop.get_netlist()`. Now things are running smoothly here. I created a PR.

**Comment by Odyseus** [comment]
Thanks for the fix, @buzz. I would not have been able to fix this on my own (I don't have an Arch system with Cinnamon). I think that is time for me to install Cinnamon in one of my Arch systems.
