### ISSUE TITLE
add link to HELP.html file if unmet dependencies found in Multi Translator

### ISSUE THREAD

**Issue by NikoKrause** [Odyseus/CinnamonTools#53]
Hey,

If you have unmet dependencies, you get a popup information to look into ~/.cinnamon/glass.log.
If you look into the glass log it says "Check this extension help file for instructions."

Why to go a long way round, if you can go the direct way?
You can add a link to the popup message to the HELP.html file. Clicking on it, opens the help file:
![screenshot-cinnamon-2017-05-01-214643](https://cloud.githubusercontent.com/assets/8415124/25592324/b110d714-2eb8-11e7-8830-36b6e645a0f8.png)

The code for this looks like this:
![screenshot-area-2017-05-01-214729](https://cloud.githubusercontent.com/assets/8415124/25592344/c0d7268a-2eb8-11e7-810e-408bccd0a83e.png)

That's something I saw on the Capture applet by rjanja. Maybe you find a way to make it look better?

**Comment by NikoKrause** [comment]
Here is HELP-de.md file for Multi-Translator
https://gist.github.com/NikoKrause/a66a41890cd64f2bb3f1a598444885d7

**Comment by Odyseus** [comment]
Hello, @NikoKrause.

> Why to go a long way round, if you can go the direct way?

This *long way* approach was done on purpose. The glass.log file will list exactly which dependencies weren't found. It's of no use to display de help file without knowing which dependencies are missing. I initially did something similar to what you propose here. The notification listed the missing dependencies and it had the link to the help file. But when you clicked the notification to open the help file, the notification was dismissed if clicked accidentally outside the link in it, which will cause the loss of the list of missing dependencies. In addition, all `Main.notify` functions doesn't have the ability to display markup, which causes the notification to look ugly.

I will try to implement something that gives direct access to more detailed information. But, whatever I do, I can't do nothing to prevent issues [like this one](https://github.com/linuxmint/cinnamon-spices-applets/issues/281) (¬¬).

***

Than you very much for the translation. You can remove it if you want/need to.

I have to use a couple of localized strings in another file (HELP.pug). Just to confirm, the following two strings are correct?

- The name of your language in your own language is "Deutsche"? This string is used in the language selector button.
- The string "Multi Translator extension help" translates into German to "Multi-Übersetzer Erweiterung Hilfe"? This string is used as the title of the page when the German language is selected.

Yeah, I know. It's annoying. I promise, I will find a better way to translate the help pages.

**Comment by NikoKrause** [comment]
The language is called "Deutsch"
And "Hilfe für die Erweiterung Multi-Übersetzer".

**Comment by NikoKrause** [comment]
The About section says Cinnamon Tweaks.

**Comment by NikoKrause** [comment]
Settings -> History -> Timestamp for history entries -> "Custom" is not translated

**Comment by NikoKrause** [comment]
And here is the tranlation po file:
https://gist.github.com/NikoKrause/9df475a344c064e5305806b6430221a5

**Comment by Odyseus** [comment]
> The About section says Cinnamon Tweaks.

Ups. Consequence of reusing code. LOL


> Settings -> History -> Timestamp for history entries -> "Custom" is not translated

> EDIT: "pixels" and "European" is also not translated

> EDIT: Appeareance -> Dialog theme -> "Default" not translated

All of these were already fixed [a couple of weeks ago](https://github.com/Odyseus/CinnamonTools/commit/f6a9792b37f93872214181492afe767dfed22596#diff-3258501c2199a2be26a70b5f9f125301R346). You must be using the extension from Spices.

> EDIT: Logs to help user are not translated

Done.

You will need to re-base your .po file with the new one from this repository.

**Comment by NikoKrause** [comment]
Updated https://gist.github.com/NikoKrause/9df475a344c064e5305806b6430221a5

**Comment by Odyseus** [comment]
Thanks, @NikoKrause.

You can *clean up* your gists now if you want/need to. 👍

**Comment by Odyseus** [comment]
Hello, @NikoKrause.

Now the notification that informs about missing dependencies will look like this:

![newnotimultitrans](https://cloud.githubusercontent.com/assets/3822556/25719667/8b904b30-30e0-11e7-962b-1f268659e1ac.png)
