### ISSUE TITLE
PopupTranslator: unmet dependencies

### ISSUE THREAD

**Issue by Ilis** [Odyseus/CinnamonTools#58]
Applet warn about unmet dependencies but there are no details in glass.log.

ilis@deore ~ $ inxi -xxxSc0 -! 31
System:    Kernel: 4.4.0-72-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.2.7 (Gtk 3.18.9-1ubuntu3.3) dm: mdm Distro: Linux Mint 18.1 Serena
ilis@deore ~ $ pastebin .cinnamon/glass.log
https://gist.github.com/71e1b7a456085b89b10fca81c72cc4be
ilis@deore ~ $ pastebin .xsession-errors 
https://gist.github.com/9572a03952797c6ac0458259ca973082

ilis@deore ~ $ which python
/usr/bin/python
ilis@deore ~ $ file /usr/bin/python
/usr/bin/python: symbolic link to python2.7

ilis@deore ~ $ ls /usr/bin/pyth*
/usr/bin/python  /usr/bin/python2  /usr/bin/python2.7  /usr/bin/python3  /usr/bin/python3.5  /usr/bin/python3.5m  /usr/bin/python3m

ilis@deore ~ $ xsel --version
xsel version 1.2.0 by Conrad Parker <conrad@vergenet.net>
ilis@deore ~ $ xdg-open --version
xdg-open 1.1.0 rc3

**Comment by Odyseus** [comment]
Hello, @Ilis.

I found the problem. I don't know what happened exactly, but it seems that I accidentally removed the execution permissions of the file **appletHelper.py** that's found inside the applet folder.

In the mean time, you can set the execution permission for that file, restart Cinnamon and the applet will inform you that all dependencies are met and nothing should display about dependencies on the applet tooltip.

I will fix it and publish it right away.

Thanks for your feedback, @Ilis.

**Comment by Odyseus** [comment]
@Ilis: Since you are on Cinnamon 3.2.x, the file **appletHelper.py** that you need to change the permissions to is inside the folder called **3.2**.
