### ISSUE TITLE
PopupTranslator: history window is empty

### ISSUE THREAD

**Issue by Ilis** [Odyseus/CinnamonTools#60]
I made some translation, then opened History window and it is empty.

But history file seems to contain my recently translations:
ilis@deore ~ $ head ./.cinnamon/configs/0dyseus@PopupTranslatorHistory/translation_history.json 
{"__version__":1,"ru":{"Popup":{"d":"2017-05-07 15:40:25","sL":"en","tL":"ru","tT":"Выскакивать"},"Important notes about Yandex API ...

ilis@deore ~ $ pastebin ./.cinnamon/configs/0dyseus@PopupTranslatorHistory/translation_history.json
https://gist.github.com/00649fad9b72194e176be1e2877bb654

System: Kernel: 4.4.0-72-generic x86_64 (64 bit gcc: 5.4.0)
Desktop: Cinnamon 3.2.7 (Gtk 3.18.9-1ubuntu3.3) dm: mdm Distro: Linux Mint 18.1 Serena

**Comment by Odyseus** [comment]
Hello, @Ilis.

Yes, I found out that problem as well. It is another annoyance that caused me to remove *multiversion* from the rest of my applets. A fix is comming.

You can remove the folder called **3.2** from the installed applet, restart Cinnamon and then your history should be displayed normally.

Again, thanks for the feedback. :+1:
