### ISSUE TITLE
[menu-applet] leaving menu open, when clearing recent file breaks keynavigation

### ISSUE THREAD

**Issue by NikoKrause** [Odyseus/CinnamonTools#7]
I saw, that you have decided to not close the menu, when the Clear Recent files button is pressed.
The problem is, that it breaks the keynavigation totally, i.e. after clearing the recent files, pressing the keys to navigate through the menu, doesn't work.

To something different:
The menu label won't be translated by default. Is it supposed to behave like that? If not try adding `_()` like that:
`this.set_applet_label(_(this.pref_custom_label_for_applet));`

**Comment by Odyseus** [comment]
Hello, @NikoKrause.

Seems that we can't catch a break with the menu applet! LOL

I decided to revert back the closing of the menu after clearing the recent files list. Trying to fix that would involve (I suppose) dealing with the keyboard navigation code. I don't want to touch that on my Custom Menu applet just yet.

About the non translated applet label. No, it isn't supposed to behave like that. You were right, I omitted the call to `_()`. Thanks for the feedback.

**Comment by NikoKrause** [comment]
@Odyseus 
It's possible to rescue the keynavigation and leaving the menu open.
I have almost a solution (for the original menu-applet). Only one thing bothers me in that solution.
When you go to the favBox right after you cleared the recent files, you get trapped in the favBox.
I have a workaround, which prevents me to be able to go to the favBox, but I'm not happy with that.

If you want to try it, I could send you the files to test it. Maybe you'll come up with a better solution?

**Comment by Odyseus** [comment]
Hello, @NikoKrause.

I wouldn't be of any help to you. The reason for not wanting to deal with the keyboard navigation code is because I barely understand it and its dozens of conditions don't help much.
