### ISSUE TITLE
Favorites' icon size scalates down when there is still space.

### ISSUE THREAD

**Issue by copecu** [Odyseus/CinnamonTools#8]
You can see the image attached for consider if that is necessary to be addressed.

```
csm@router ~ $ inxi -Sxxx
System:    Host: router Kernel: 4.4.0-45-generic x86_64 (64 bit gcc: 5.4.0)
                Desktop: Cinnamon 3.0.7 (Gtk 3.18.9) dm: mdm Distro: Linux Mint 18 Sarah
```

Thank you.

![captura de pantalla de 2016-11-06 11-40-04](https://cloud.githubusercontent.com/assets/5006044/20037171/3206af84-a41b-11e6-9fe3-ca15306ce6c0.png)

**Comment by Odyseus** [comment]
Hello, @copecu.

Thanks for the report. I was aware of that behaviour and I already have it fixed for the next version of this applet. I have not noticed it before because I use the favorites box hidden at all times.
