### ISSUE TITLE
Concidered help on windows decoration

### ISSUE THREAD

**Issue by lestcape** [Odyseus/CinnamonTools#9]
Hi, i see you have a maximum applet, so probably you are interesting on that. I currently try to add this functionality inside the muffin windows manager. The problem it's that, development this is pretty complex and slower...

I don't know if you have skill on what supposed to be muffin. I don't have any skill, but waverer i create this : https://github.com/linuxmint/muffin/pull/269 

Currently this is working to undecorated a windows, but not is working to decorated the windows. The problem begin, when i change this:
https://github.com/linuxmint/muffin/pull/269/commits/5b20b0df103624b5442785df9950eb21f11f4a24#diff-029d285c3238fbe60d57f513265e1723R8417
for this:

```
  if (window->hide_titlebar_when_maximized &&
     //(window->type != META_FRAME_TYPE_BORDER) &&
     !meta_window_is_client_decorated (window))
    {
      gboolean old_decorated = window->decorated;
      MetaWindowType old_type = window->type;
      if (META_WINDOW_MAXIMIZED (window))
        {
          window->decorated = FALSE;
          window->type = META_FRAME_TYPE_BORDER;
          meta_warning (_("Failed to open debug log: %s\n"), "called False");
        } else
        {
          window->decorated = TRUE;
          meta_warning (_("Failed to open debug log: %s\n"), "called True");
        }
          GObject  *object = G_OBJECT (window);

          if (!window->override_redirect)
            set_net_wm_state (window);

          meta_warning (_("Will enter: %d\n"), window->decorated);
          // Update frame
          if (window->decorated) {
            meta_window_ensure_frame (window);
            meta_warning (_("Enter: %s\n"), "called True");
          } else {
            meta_window_destroy_frame (window);
            meta_warning (_("Enter: %s\n"), "called False");
          }

          // update stacking constraints
          meta_window_update_layer (window);

          meta_window_grab_keys (window);

          g_object_freeze_notify (object);

          if (old_decorated != window->decorated)
            g_object_notify (object, "decorated");

          g_object_notify (object, "window-type");

          g_object_thaw_notify (object);
  }
```
The decoration occurs in function:
```
             meta_window_ensure_frame (window);
```

but there are something missing, because in some point before this call, cinnamon crash (freezes), with an error about to pixmap bugs.

Another question your speak Spanish?

Regards....

**Comment by Odyseus** [comment]
Hola, @lestcape.

Sí, hablo español.

Sí, estoy muy interesado en esa funcionalidad que tú intentas agregar a **muffin**. De hecho, **mutter** la tiene implementada y la nueva extensión llamada [Maximus NG](https://github.com/luispabon/maximus-gnome-shell) hace uso de ese método para remover las barras de título de las ventanas. Tiene una opción llamada **Use alternate method for hiding the titlebar** que es mucho más estable que el tradicional uso de **xprop**.

Por desgracia, no puedo ayudarte a solucionar ese problema con **muffin**. No estoy familiarizado con el lenguaje C. Yo no soy un desarrollador profesional.

**Comment by lestcape** [comment]
jajaja, pues pareces bastante profesional, si te refieres a un titulo o algo, no hace falta tal cosa... Los hechos dicen mas de 1000 palabras.

No se si es cinnamon 3.2 o que diablos pasa, pero tu extension no funciona. Con ella me puse a buscar que era lo que hacia muffin por dentro y para nada hace lo que yo esperaba que hicera, por lo que al parecer la extension utiliza llamadas a programas que operan a otro nivel diferente de muffin.

Lo que hice fue imprimir mensages donde muffin cambia la decoracion de las ventanas... Los mensajes no se imprimen, luego no llega a muffin la llamada.

Tu extension tiene aproximadamente el mismo problema que lo que me pasa, es cuando decoras las ventanas, a veces no se decoran.. firefox sobre todo...

**Comment by lestcape** [comment]
Me puedes dar una referencia a de donde sacas **Use alternate method for hiding the titlebar**, ni idea de que hablas..

**Comment by lestcape** [comment]
ahhh, si te refieres a el metodo alternativo solo valido para aplicaciones gtk+. en muffin quitaron el soporte y es lo que estoy tratando de volver a poner, para partir de alguna parte.

**Comment by lestcape** [comment]
ya vi el codigo de la extensi'on, ni modo... No tiene nada que no sepa.

**Comment by lestcape** [comment]
Ya por fin logre hacer esto, por donde iba no salia bien, porque decoraba la ventana y esto en cinnnamon es equivalente a volver a crear la ventanta desde cero.... Lo cual no puede hacerse si capturaste algun evento de teclado y estas en un drag and drop, porque se queda inconcistente el evento, ya que la ventana que lo ocacionó, se destruyó y se creó una nueva en su lugar.

Ahora lo que hago es decirle a la ventana que se repinte, pero sin bordes... No le quito la decoración y esto hace que no se cree un nuevo actor y que además se haga en un segundo el proceso.

Ahora estoy viendo si le pongo lo mismo al windowsmanager, porque lo que hice es para cada ventana en particular y entonces serìa bueno tener un metodo global, para que con solo llamar a una función se active la el efecto de maximun.

Es decir, un método de esta clase:
https://github.com/linuxmint/Cinnamon/blob/04527cab1070bd14749d499957afb100ce60dbef/js/ui/windowManager.js#L405

**Comment by Odyseus** [comment]
Hola, @lestcape.

Si te parece bien, me gustaría usar este "issue" para hacerte un par de consultas. Mis dudas no son urgentes, así que respóndeme si puedes cuando tengas unos minutos libres.

En uno de los mensajes del "issue" en el repositorio de NikoKrause, tú enlazaste [a otro "issue" abierto por tí](https://github.com/linuxmint/Cinnamon/issues/4984#issuecomment-168654184). En ese "issue" comentas sobre los menúes en Cinnamon:

> Another thing is about the current behaviour of not open a popup menu if other popup menu is open. I consider, that this is a bad restriction and cause to the user a duplicate enforce to realize his action. This behaviour can easy change if we return false instead of true here:

Yo detesto que los menúes en Cinnamon no puedan ser abiertos sin primero cerrar el menú que está actualmente abierto. Me costó encontrar dónde se cambia ese comportamiento (porque los enlaces que tú has publicado no apuntan a las líneas de código correctas debido a que el archivo a cambiado con el tiempo), pero ya he encontrado cómo hacerlo y ya lo he implementado en mi extensión llamada Cinnamon Tweaks (todavía no he subido los cambios a mi repositorio).

Mi pregunta es la siguiente. ¿Sería posible reproducir el comportamiento de los menúes como en Gnome Shell? En Gnome Shell, si tú abres un menú en el panel superior y luego mueves el cursor del ratón sobre otro "applet" con un menú, el menú se abre automáticamente sin tener que hacer click. ¿Es posible hacer esto mismo en Cinnamon con unas simples modificaciones? ¿O requeriría un cambio muy drástico?

**Comment by lestcape** [comment]
@Odyseus claro, en lo que pueda ayudar, si es que puedo. Disculpa, pero no entiendo como es tu forma de trabajo... Es decir, ¿tu intención con esto cual es? ¿Una forma general para todo applet o una forma específica de un applet? La de una applet me imagino que no es, porque se que sabes que esto es una opción del menú principal de cinnamon...

Para hacer algo general, pasate por este comentario y el siguiente:
https://github.com/linuxmint/Cinnamon/pull/5974#issuecomment-261157029

En otras palabras no hay una buena forma de hacer esto en general, desde una extensión porque no tienes acceso al código.

Si lo que quieres es modificar el código interno de cinnamon para hacer esto, entonces si es posible usando esta clase y presuponiendo que todos los applets la usan para crear su menú:
https://github.com/linuxmint/Cinnamon/blob/master/js/ui/applet.js#L82

Solo conecta el launcher.actor a leave y enter event como en el menú principal:

https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/applets/menu%40cinnamon.org/applet.js#L1292

**Comment by Odyseus** [comment]
Hello, @lestcape.

Si nunca has usado Gnome Shell, es complicado de explicar lo que yo quiero hacer.

Voy a tratar de explicarlo con una imagen animada. En [esta imagen](https://cloud.githubusercontent.com/assets/3822556/20537114/93972858-b0ca-11e6-98a5-c534bb3c5d23.gif) se ve como primero abro el menú aplicaciones haciendo clic en él, y luego muevo el cursor del ratón hacia otros botones en el panel y los menúes se abren sin hacer clic en ellos.

No, no quiero que todos los menúes del panel se abran con solo pasar el ratón sobre ellos. Quiero reproducir el comportamiento de Gnome Shell, abrir un menú normalmente haciendo clic, y luego que los demás menúes se abran al pasar el ratón, pero sólo si ya hay otro menú abierto.

Espero que se haya entendido.

> En otras palabras no hay una buena forma de hacer esto en general, desde una extensión porque no tienes acceso al código.

Esto no es del todo cierto. Yo lo hago constantemente en mi extensión [Cinnamon Tweaks](https://github.com/Odyseus/CinnamonTools/blob/master/Extensions/0dyseus%40CinnamonTweaks/extension.js). De hecho, todos los tweaks que yo he agregado a esa extensión hacen lo mismo, sobre-escribir las funciones originales de Cinnamon por funciones modificada por mí. En algunos casos especiales, no necesito sobre-escribir la función original, sino que inyecto algo de código a la función original.

**Comment by lestcape** [comment]
Ya etiendo que quieres hacer. A ver si me explico lo que yo creo, no es que sea cierto, pero es lo que creo.

La disyuntiva con esto es que no quieres el context menu, tu quieres el menu que se despliega con el click izquierdo... Cierto? Bueno a eso me refiero cuando digo que no se puede de una buena forma, porque el menu contextual, se crea en la clase applet, pero el menu del clic izquierdo no. Entonces, no sabes el nombre que va a tener el menu del click izquierdo, ya que el autor del applet, puede elegir el nombre que le de la gana ponerle (no necesariamente se va a llamar menu).

Ahora la disyuntiva, como encuentras el menu? Sin dudas esto es super importante, ya que es el comportamiento de ese menu específico que no sabes como se llama el que quieres modificar...

Supon que encuentres el menu, esto no es suficiente porque quieres modificar un comportamiento global y estos están definidos en la clase menu manager, que tambien vas a tener que encontrar y que puede tener cualquier nombre al igual que el menu. De hecho puedes tener un menumanager para el context menu y otra instancia de menumanager para el menú del click izquierdo (no tienen porque ser la misma).

A esto me refiero en los dos comentarios y si te fijas pongo un algoritmo para "resolver el problema".

Lo que quieres hacer es lo que yuo hice con los indicadores. Cambia a modo de indicadores en cinnamon-settings. Instalate dos o tres indicadores y prueba que funciona como tu quieres que ocurra.

**Comment by Odyseus** [comment]
@lestcape
Oh!! Ahora entiendo perfectamente lo que has querido decir antes! Yo fui el que entendió mal lo que habías dicho.

> A esto me refiero en los dos comentarios y si te fijas pongo un algoritmo para "resolver el problema".

Sí, he visto el código de ejemplo en ese "issue". Eso fue lo primero que se me ocurrió, pero lo consideré un poco "exagerado" de implementar para los applets.

> Lo que quieres hacer es lo que yuo hice con los indicadores.

Exactamente eso es lo que quiero hacer. Nunca lo había visto en los indicadores porque los tengo deshabilitados (no me gusta para nada esa función). ¿Quién es el "responsable" de que los menúes de los indicadores funcionen de esa manera? No me doy cuenta en dónde está definido ese comportamiento.

**Comment by lestcape** [comment]
Claro, por eso digo "resolver el problema", ese código es una basura, no sirve, pero al menos yo no veo otra forma, por lo que creo conveniente que cada vez que se cree una instancia the menu manager, esta se registre en alguna instancia en Main, para que puedas acceder luego a los menu manager, sin necesitad de explorar todos los atributos de la instancia de cada clase applet, que además, no necesariamente tiene un menu manager a primer nivel del objeto, porque puede estar dentro de otro objecto (un wrapper) y entonces aunque explores, no la vas a encontrar.

De los indicadores:
Pues está  algo dificil de referenciar, es que el menu manager está esperando un actor con un applet como delegado, pero los actores de los indicadores no son actores de la clase applet, sino que son hijos del actor del applet, por lo que se saltan la restricción del menu manager y funcionan como si fuese gnome shell.

**Comment by Odyseus** [comment]
Hola, @lestcape.

Creo que voy a dejar "descansar" este tema por el momento. Resultó ser bastante complicado de implementar. Incluso he pasado horas viendo el código fuente de Gnome Shell y no he encontrado ninguna pista al respecto.

De todos modos, estoy inmensamente agradecido por tu ayuda y tu tiempo. El sólo hecho de que pude cambiar el comportamiento de los menúes (como he comentado en [este mensaje](https://github.com/Odyseus/CinnamonTools/issues/9#issuecomment-262101237)) me hace súper feliz.

Si en el futuro encuentro alguna manera de resolver lo que estuvimos hablando, te voy a informar por aquí.

:+1:

**Comment by lestcape** [comment]
Añadido:
```
const Applet = imports.ui.applet;
```

```
function PopupMenuManager(owner) {
    this._init(owner);
}

PopupMenuManager.prototype = {

....................................................

    _onMenuSourceEnter: function(menu) {
```
Añadido:
```
        if(menu.sourceActor && menu.sourceActor._applet && menu instanceof Applet.AppletPopupMenu) {
            menu.open(true);
            return false;
        }
```
```
        if (!this.grabbed || menu == this._activeMenu)
            return false;

        if (this._activeMenu && this._activeMenu.isChildMenu(menu))
            return false;

        if (this._menuStack.indexOf(menu) != -1)
            return false;

        if (this._menuStack.length > 0 && this._menuStack[0].isChildMenu(menu))
            return false;

        this._changeMenu(menu);
        return false;
    },

.................................................................

    _onEventCapture: function(actor, event) {
        if (!this.grabbed)
            return false;

        if (Main.keyboard.shouldTakeEvent(event))
            return Clutter.EVENT_PROPAGATE;

        if (this._owner.menuEventFilter &&
            this._owner.menuEventFilter(event))
            return true;

        if (this._activeMenu != null && this._activeMenu.passEvents)
            return false;

        if (this._didPop) {
            this._didPop = false;
            return true;
        }

        let activeMenuContains = this._eventIsOnActiveMenu(event);
        let eventType = event.type();

        if (eventType == Clutter.EventType.BUTTON_RELEASE) {
            if (activeMenuContains) {
                return false;
            } else {
                this._closeMenu();
```
cambio en el retorno:
```
                return false;
```
```
            }
        } else if (eventType == Clutter.EventType.BUTTON_PRESS && !activeMenuContains) {
            this._closeMenu();
```
cambio en el retorno:
```
            return false;
```
```
        } else if (!this._shouldBlockEvent(event)) {
            return false;
        }
```
Añadido:
```
        for (let menu in this._menus) {
            if(menu.sourceActor.contains(actor))
               return false;
        }
```
```
        return true;
    },
}
```

**Comment by lestcape** [comment]
Quedaría algo como esto, pero esto, por supuesto, tienes que inyectarlo. Esto es solo para que lo pruebes. Reemplazalo en popupmenu.js

```
/* Basic implementation of a menu manager.
 * Call addMenu to add menus
 */
function PopupMenuManager(owner) {
    this._init(owner);
}

PopupMenuManager.prototype = {
    _init: function(owner) {
        this._owner = owner;
        this.grabbed = false;

        this._eventCaptureId = 0;
        this._enterEventId = 0;
        this._leaveEventId = 0;
        this._keyFocusNotifyId = 0;
        this._activeMenu = null;
        this._menus = [];
        this._menuStack = [];
        this._preGrabInputMode = null;
        this._grabbedFromKeynav = false;
        this._signals = new SignalManager.SignalManager(this);
    },

    addMenu: function(menu, position) {
        this._signals.connect(menu, 'open-state-changed', this._onMenuOpenState);
        this._signals.connect(menu, 'child-menu-added', this._onChildMenuAdded);
        this._signals.connect(menu, 'child-menu-removed', this._onChildMenuRemoved);
        this._signals.connect(menu, 'destroy', this._onMenuDestroy);

        let source = menu.sourceActor;

        if (source) {
            this._signals.connect(source, 'enter-event', function() { this._onMenuSourceEnter(menu); });
            this._signals.connect(source, 'key-focus-in', function() { this._onMenuSourceEnter(menu); });
        }

        if (position == undefined)
            this._menus.push(menu);
        else
            this._menus.splice(position, 0, menu);
    },

    removeMenu: function(menu) {
        if (menu == this._activeMenu)
            this._closeMenu();

        let position = this._menus.indexOf(menu);

        if (position == -1) // not a menu we manage
            return;

        this._signals.disconnect(null, menu);

        if (menu.sourceActor)
            this._signals.disconnect(null, menu.sourceActor);

        this._menus.splice(position, 1);
    },

    _grab: function() {
        if (!Main.pushModal(this._owner.actor)) {
            return;
        }
        this._signals.connect(global.stage, 'captured-event', this._onEventCapture);
        // captured-event doesn't see enter/leave events
        this._signals.connect(global.stage, 'enter-event', this._onEventCapture);
        this._signals.connect(global.stage, 'leave-event', this._onEventCapture);
        this._signals.connect(global.stage, 'notify::key-focus', this._onKeyFocusChanged);

        this.grabbed = true;
    },

    _ungrab: function() {
        if (!this.grabbed) {
            return;
        }

        this._signals.disconnect(null, global.stage);

        this.grabbed = false;
        Main.popModal(this._owner.actor);
    },

    _onMenuOpenState: function(menu, open) {
        if (open) {
            if (this._activeMenu && this._activeMenu.isChildMenu(menu)) {
                this._menuStack.push(this._activeMenu);
                menu.actor.grab_key_focus();
            }
            this._activeMenu = menu;
        } else {
            if (this._menuStack.length > 0) {
                this._activeMenu = this._menuStack.pop();
                if (menu.sourceActor)
                    menu.sourceActor.grab_key_focus();
                this._didPop = true;
            }
        }

        // Check what the focus was before calling pushModal/popModal
        let focus = global.stage.key_focus;
        let hadFocus = focus && this._activeMenuContains(focus);

        if (open) {
            if (!this.grabbed) {
                this._preGrabInputMode = global.stage_input_mode;
                this._grabbedFromKeynav = hadFocus;
                this._grab();
            }

            if (hadFocus)
                focus.grab_key_focus();
            else
                menu.actor.grab_key_focus();
        } else if (menu == this._activeMenu) {
            if (this.grabbed)
                this._ungrab();
            this._activeMenu = null;

            if (this._grabbedFromKeynav) {
                if (this._preGrabInputMode == Cinnamon.StageInputMode.FOCUSED)
                    global.stage_input_mode = Cinnamon.StageInputMode.FOCUSED;
                if (hadFocus && menu.sourceActor)
                    menu.sourceActor.grab_key_focus();
                else if (focus)
                    focus.grab_key_focus();
            }
        }
    },

    _onChildMenuAdded: function(menu, childMenu) {
        this.addMenu(childMenu);
    },

    _onChildMenuRemoved: function(menu, childMenu) {
        this.removeMenu(childMenu);
    },

    // change the currently-open menu without dropping grab
    _changeMenu: function(newMenu) {
        if (this._activeMenu) {
            // _onOpenMenuState will drop the grab if it sees
            // this._activeMenu being closed; so clear _activeMenu
            // before closing it to keep that from happening
            let oldMenu = this._activeMenu;
            this._activeMenu = null;
            for (let i = this._menuStack.length - 1; i >= 0; i--)
                this._menuStack[i].close(false);
            oldMenu.close(false);
            newMenu.open(false);
        } else
            newMenu.open(true);
    },

    _onMenuSourceEnter: function(menu) {
        if(menu.sourceActor && menu.sourceActor._applet && menu instanceof Applet.AppletPopupMenu) {
            menu.open(true);
            return false;
        }

        if (!this.grabbed || menu == this._activeMenu)
            return false;

        if (this._activeMenu && this._activeMenu.isChildMenu(menu))
            return false;

        if (this._menuStack.indexOf(menu) != -1)
            return false;

        if (this._menuStack.length > 0 && this._menuStack[0].isChildMenu(menu))
            return false;

        this._changeMenu(menu);
        return false;
    },

    _onKeyFocusChanged: function() {
        if (!this.grabbed || !this._activeMenu || DND.isDragging())
            return;

        let focus = global.stage.key_focus;
        if (focus) {
            if (this._activeMenuContains(focus))
                return;
            if (this._menuStack.length > 0)
                return;
            if (focus._delegate && focus._delegate.menu &&
                this._menus.indexOf(focus._delegate.menu) != -1)
                return;
        }

        this._closeMenu();
    },

    _onMenuDestroy: function(menu) {
        this.removeMenu(menu);
    },

    _activeMenuContains: function(actor) {
        return this._activeMenu != null
                && (this._activeMenu.actor.contains(actor) ||
                    (this._activeMenu.sourceActor && this._activeMenu.sourceActor.contains(actor)));
    },

    _eventIsOnActiveMenu: function(event) {
        return this._activeMenuContains(event.get_source());
    },

    _shouldBlockEvent: function(event) {
        let src = event.get_source();

        if (this._activeMenu != null && this._activeMenu.actor.contains(src))
            return false;

        return (this._menus.find(x => x.sourceActor &&
                                      !x.blockSourceEvents &&
                                      x.sourceActor.contains(src)) === undefined);
    },

    _onEventCapture: function(actor, event) {
        if (!this.grabbed)
            return false;

        if (Main.keyboard.shouldTakeEvent(event))
            return Clutter.EVENT_PROPAGATE;

        if (this._owner.menuEventFilter &&
            this._owner.menuEventFilter(event))
            return true;

        if (this._activeMenu != null && this._activeMenu.passEvents)
            return false;

        if (this._didPop) {
            this._didPop = false;
            return true;
        }

        let activeMenuContains = this._eventIsOnActiveMenu(event);
        let eventType = event.type();

        if (eventType == Clutter.EventType.BUTTON_RELEASE) {
            if (activeMenuContains) {
                return false;
            } else {
                this._closeMenu();
                return false;
            }
        } else if (eventType == Clutter.EventType.BUTTON_PRESS && !activeMenuContains) {
            this._closeMenu();
            return false;
        } else if (!this._shouldBlockEvent(event)) {
            return false;
        }
        for (let menu in this._menus) {
            if(menu.sourceActor.contains(actor))
               return false;
        }

        return true;
    },

    _closeMenu: function() {
        if (this._activeMenu != null)
            this._activeMenu.close(true);
    }
};
```

**Comment by Odyseus** [comment]
Hola, @lestcape.

:clap: (Un aplauso!!!) 

Aunque tus modificaciones no hacen exactamente lo que yo quiero lograr, con un par de retoques logré hacerlo funcionar exactamente como Gnome Shell.

Básicamente lo que hice fue guardar en **Main.allAppletsMenus** todos los menúes que me interesan. Luego, dentro de **_onMenuSourceEnter**, chequeo si hay un menú abierto o no antes de decidir si el menú del applet que está actualmente debajo del ratón tiene que ser abierto o no.

Este es el código completo modificado:

```javascript
const Applet = imports.ui.applet;

/* Basic implementation of a menu manager.
 * Call addMenu to add menus
 */
function PopupMenuManager(owner) {
    this._init(owner);
}

PopupMenuManager.prototype = {
    _init: function(owner) {
        this._owner = owner;
        this.grabbed = false;

        /**
         * Primero creo un "array" global para guardar todos los menúes que quiero "manejar".
         */
        if (!Main.allAppletsMenus)
            Main.allAppletsMenus = [];

        this._eventCaptureId = 0;
        this._enterEventId = 0;
        this._leaveEventId = 0;
        this._keyFocusNotifyId = 0;
        this._activeMenu = null;
        this._menus = [];
        this._menuStack = [];
        this._preGrabInputMode = null;
        this._grabbedFromKeynav = false;
        this._signals = new SignalManager.SignalManager(this);
    },

    addMenu: function(menu, position) {
        this._signals.connect(menu, 'open-state-changed', this._onMenuOpenState);
        this._signals.connect(menu, 'child-menu-added', this._onChildMenuAdded);
        this._signals.connect(menu, 'child-menu-removed', this._onChildMenuRemoved);
        this._signals.connect(menu, 'destroy', this._onMenuDestroy);

        let source = menu.sourceActor;

        if (source) {
            this._signals.connect(source, 'enter-event', function() {
                this._onMenuSourceEnter(menu);
            });
            this._signals.connect(source, 'key-focus-in', function() {
                this._onMenuSourceEnter(menu);
            });

            /**
             * Cada vez que addMenu es llamado desde un applet,
             * va a guardar el menú que quiero "manejar" en Main.allAppletsMenus.
             */
            if (Main.allAppletsMenus.indexOf(menu) === -1 &&
                source._applet &&
                menu instanceof Applet.AppletPopupMenu)
                Main.allAppletsMenus.push(menu);
        }

        if (position == undefined)
            this._menus.push(menu);
        else
            this._menus.splice(position, 0, menu);
    },

    removeMenu: function(menu) {
        if (menu == this._activeMenu)
            this._closeMenu();

        let position = this._menus.indexOf(menu);

        if (position == -1) // not a menu we manage
            return;

        this._signals.disconnect(null, menu);

        if (menu.sourceActor)
            this._signals.disconnect(null, menu.sourceActor);

        this._menus.splice(position, 1);

        /**
         * "Limpiar" el menú que acaba de set removido de Main.allAppletsMenus.
         */
        if (Main.allAppletsMenus.indexOf(menu) !== -1)
            Main.allAppletsMenus.splice(Main.allAppletsMenus.indexOf(menu), 1);
    },

    _grab: function() {
        if (!Main.pushModal(this._owner.actor)) {
            return;
        }
        this._signals.connect(global.stage, 'captured-event', this._onEventCapture);
        // captured-event doesn't see enter/leave events
        this._signals.connect(global.stage, 'enter-event', this._onEventCapture);
        this._signals.connect(global.stage, 'leave-event', this._onEventCapture);
        this._signals.connect(global.stage, 'notify::key-focus', this._onKeyFocusChanged);

        this.grabbed = true;
    },

    _ungrab: function() {
        if (!this.grabbed) {
            return;
        }

        this._signals.disconnect(null, global.stage);

        this.grabbed = false;
        Main.popModal(this._owner.actor);
    },

    _onMenuOpenState: function(menu, open) {
        if (open) {
            if (this._activeMenu && this._activeMenu.isChildMenu(menu)) {
                this._menuStack.push(this._activeMenu);
                menu.actor.grab_key_focus();
            }
            this._activeMenu = menu;
        } else {
            if (this._menuStack.length > 0) {
                this._activeMenu = this._menuStack.pop();
                if (menu.sourceActor)
                    menu.sourceActor.grab_key_focus();
                this._didPop = true;
            }
        }

        // Check what the focus was before calling pushModal/popModal
        let focus = global.stage.key_focus;
        let hadFocus = focus && this._activeMenuContains(focus);

        if (open) {
            if (!this.grabbed) {
                this._preGrabInputMode = global.stage_input_mode;
                this._grabbedFromKeynav = hadFocus;
                this._grab();
            }

            if (hadFocus)
                focus.grab_key_focus();
            else
                menu.actor.grab_key_focus();
        } else if (menu == this._activeMenu) {
            if (this.grabbed)
                this._ungrab();
            this._activeMenu = null;

            if (this._grabbedFromKeynav) {
                if (this._preGrabInputMode == Cinnamon.StageInputMode.FOCUSED)
                    global.stage_input_mode = Cinnamon.StageInputMode.FOCUSED;
                if (hadFocus && menu.sourceActor)
                    menu.sourceActor.grab_key_focus();
                else if (focus)
                    focus.grab_key_focus();
            }
        }
    },

    _onChildMenuAdded: function(menu, childMenu) {
        this.addMenu(childMenu);
    },

    _onChildMenuRemoved: function(menu, childMenu) {
        this.removeMenu(childMenu);
    },

    // change the currently-open menu without dropping grab
    _changeMenu: function(newMenu) {
        if (this._activeMenu) {
            // _onOpenMenuState will drop the grab if it sees
            // this._activeMenu being closed; so clear _activeMenu
            // before closing it to keep that from happening
            let oldMenu = this._activeMenu;
            this._activeMenu = null;
            for (let i = this._menuStack.length - 1; i >= 0; i--)
                this._menuStack[i].close(false);
            oldMenu.close(false);
            newMenu.open(false);
        } else
            newMenu.open(true);
    },

    _onMenuSourceEnter: function(menu) {
        if (menu.sourceActor && menu.sourceActor._applet && menu instanceof Applet.AppletPopupMenu) {
            /**
             * No sé si esto es necesario.
             * Lo agregué sólo para que el loop que le sigue no se ejecute tanto.
             */
            if (menu == this._activeMenu)
                return false;

            let allowToOpen = false;
            try {
                /**
                 * Aquí simplemene me fijo si uno de los menúes guardado en Main.allAppletsMenus está actualmente abierto.
                 * Si encuentra un menú abierto mientras estoy pasando el ratón sobre otro applet,
                 * el menú de ese applet se va a abrir.
                 * Si ninguno de los menúes guardados en Main.allAppletsMenus está actualmente abierto,
                 * nada va a suceder.
                 */
                for (let i = Main.allAppletsMenus.length - 1; i >= 0; i--) {
                    if (Main.allAppletsMenus[i].isOpen) {
                        allowToOpen = true;
                        break;
                    }
                }
            } finally {
                allowToOpen && menu.open(true);
                return false;
            }
        }

        if (!this.grabbed || menu == this._activeMenu)
            return false;

        if (this._activeMenu && this._activeMenu.isChildMenu(menu))
            return false;

        if (this._menuStack.indexOf(menu) != -1)
            return false;

        if (this._menuStack.length > 0 && this._menuStack[0].isChildMenu(menu))
            return false;

        this._changeMenu(menu);
        return false;
    },

    _onKeyFocusChanged: function() {
        if (!this.grabbed || !this._activeMenu || DND.isDragging())
            return;

        let focus = global.stage.key_focus;
        if (focus) {
            if (this._activeMenuContains(focus))
                return;
            if (this._menuStack.length > 0)
                return;
            if (focus._delegate && focus._delegate.menu &&
                this._menus.indexOf(focus._delegate.menu) != -1)
                return;
        }

        this._closeMenu();
    },

    _onMenuDestroy: function(menu) {
        this.removeMenu(menu);
    },

    _activeMenuContains: function(actor) {
        return this._activeMenu != null && (this._activeMenu.actor.contains(actor) ||
            (this._activeMenu.sourceActor && this._activeMenu.sourceActor.contains(actor)));
    },

    _eventIsOnActiveMenu: function(event) {
        return this._activeMenuContains(event.get_source());
    },

    _shouldBlockEvent: function(event) {
        let src = event.get_source();

        if (this._activeMenu != null && this._activeMenu.actor.contains(src))
            return false;

        return (this._menus.find(x => x.sourceActor &&
            !x.blockSourceEvents &&
            x.sourceActor.contains(src)) === undefined);
    },

    _onEventCapture: function(actor, event) {
        if (!this.grabbed)
            return false;

        if (Main.keyboard.shouldTakeEvent(event))
            return Clutter.EVENT_PROPAGATE;

        if (this._owner.menuEventFilter &&
            this._owner.menuEventFilter(event))
            return true;

        if (this._activeMenu != null && this._activeMenu.passEvents)
            return false;

        if (this._didPop) {
            this._didPop = false;
            return true;
        }

        let activeMenuContains = this._eventIsOnActiveMenu(event);
        let eventType = event.type();

        if (eventType == Clutter.EventType.BUTTON_RELEASE) {
            if (activeMenuContains) {
                return false;
            } else {
                this._closeMenu();
                return false;
            }
        } else if (eventType == Clutter.EventType.BUTTON_PRESS && !activeMenuContains) {
            this._closeMenu();
            return false;
        } else if (!this._shouldBlockEvent(event)) {
            return false;
        }

        /**
         * Este loop nunca va a retornar false. menu.sourceActor es siempre undefined.
         */
        // for (let menu in this._menus) {
        //  if (menu.sourceActor && menu.sourceActor.contains(actor))
        //      return false;
        // }

        /**
         * Debido a que el loop anterior no retorna false, yo tuve que cambiar este retorno a false.
         * No sé las implicaciones de hacer esto, pero al menos hice que todo funcione.
         */
        return false;
    },

    _closeMenu: function() {
        if (this._activeMenu != null)
            this._activeMenu.close(true);
    }
};
```

Tal cual está, el código funciona de maravillas. Pero no sé si necesita algunos retoques o no.

**Comment by lestcape** [comment]
Si, me quedaba claro que esto no iba a hacer exactamente lo que querías, pero básicamente te iba a poner en el camino para lograrlo.

Yo estoy casi seguro que no vas a poner lograr meter esto que has echo por defecto en cinnamon, yo sería uno de los que me opondría. Si te apoyaría, si en lugar de guardar en Main los menus que te interesan, guardas todos los menumanagers. Eso sería simplemente algo útil.

Luego desde tu extensión, simplemente puedes obtener todos los menusmanager e iterar por todos los menus, filtrando para dejar solo los que te interesan. Se resolvería tu problema y quedaría la puerta abierta a que cualquiera pueda cambiar el comportamiento de los menus. Lo cual me parece muy útil, para casos como el tuyo. 

La otra es que encuentres una buena forma de obtener todos los managers, pero yo al menos no la encuentro.

**Comment by lestcape** [comment]
Mira, no se si esto te interese:
https://github.com/linuxmint/Cinnamon/issues/5028

Abajo puse el código para resolverlo.
La clase no tiene porque estar en layout.js, donde quiera que la instancies va a funcionar... Hay varias cosas que mejorar, pero bueno...

**Comment by Odyseus** [comment]
@lestcape

Oh, nunca fue mi intensión presentar esta funcionalidad para que sea agregada por defecto a Cinnamon. Ya sabemos que los desarrolladores de Cinnamon prefieren las cosas simples y cuantas menos preferencias haya, mucho mejor.

Por el contrario, para mí, cuantas más preferencias haya, mucho mejor. Y el sistema de extensiones es perfecto para agregar funcionalidades y/o preferencias a Cinnamon. Por eso ya estoy agregando esta funcionalidad en mi extensión.

> Mira, no se si esto te interese:
> linuxmint/Cinnamon#5028

A mí en particular no me interesa esa funcionalidad porque yo no uso los íconos del escritorio (los tengo escondidos). Pero apenas vi tu comentario hace unas horas, ya pensé en agregarlo a mi extensión. Aunque voy a intentar hacerlo simple (sin el método **setPosition**). Como dije en el párrafo anterior, cuantas más opciones haya, mucho mejor (siempre y cuando no interfieran ni causen "daño", por supuesto).

Infinitas gracias, Lester. Sin tu ayuda, jamás podría haber logrado implementar estas funcionalidades por mi cuenta.

Por cierto, si tienes "más trucos bajo la manga" que podrían ser agregados a Cinnamon a través de una extensión, soy "todo oídos".

**Comment by lestcape** [comment]
Ok. Si, encuentras algun día una mejor forma de acceder a la clase popupmenu manager, me avisas, esto si me interesaría, para agregarle la funcionalidad de abrir sub-menu flotantes y poder desplegar dialogos (color chooser, open file)...

**Comment by lestcape** [comment]
Mejore un poco el procedimiento del drag and drop, creo que ahora si merece la pena usar setPosition. Crees que meresca la pena crear un pull en cinnamon con esto?

**Comment by Odyseus** [comment]
Yo creo que sí. Creo que hay varios "issues" abiertos pidiendo la funcionalidad de arrastrar aplicaciones al escritorio. Y tu método es global. O sea, no hay que agregar esa funcionalidad al menú ni al lanzador del panel.

Yo ya lo he agregado a mi extensión y funciona de maravillas. Puedo arrastrar aplicaciones desde el menú y desde los lanzadores del panel.

**Comment by lestcape** [comment]
Yes also favourites if you want.
